<a href="https://colab.research.google.com/github/shravan1808/ML_SERIES/blob/Main/03_Enterprise_Logistics_Fleet_Delay_Analytics/notebook/03_Enterprise_Logistics_Fleet_Delay_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
shipments_data = {
    'Shipment_ID': [f'SHP_{100+i}' for i in range(50)],
    'Vehicle_ID': [f'VEH_{(i%10)+1}' for i in range(50)],
    'Region_ID': [f'REG_{(i%5)+1}' for i in range(50)],
    'Distance_KM': [120, 450, 80, 600, 310, 150, 520, 210, 750, 90, 340, 180, 620, 290, 410, 110, 800, 230, 500, 140, 380, 260, 710, 190, 440, 160, 680, 220, 530, 130, 360, 270, 740, 170, 490, 150, 650, 240, 580, 200, 420, 280, 790, 180, 460, 210, 630, 250, 510, 300],
    'Cargo_Weight_Tons': [5.2, 18.0, 2.1, 22.5, 12.0, 4.5, 19.8, 8.1, 24.0, 3.0, 14.2, 6.0, 21.0, 10.5, 16.0, 4.0, 25.0, 7.5, 18.5, 5.0, 13.5, 9.0, 23.0, 6.5, 17.0, 5.5, 22.0, 8.0, 19.0, 4.8, 13.0, 9.5, 24.5, 6.2, 17.5, 5.8, 21.5, 8.5, 20.0, 7.0, 15.5, 10.0, 24.8, 6.8, 16.5, 7.8, 21.2, 8.8, 18.8, 11.0],
    'Actual_Delay_Hours': [0.5, 4.2, 0.0, 6.5, 1.2, 0.0, 5.1, 0.8, 8.0, 0.0, 2.5, 0.2, 7.1, 1.0, 3.8, 0.0, 9.2, 0.5, 4.8, 0.1, 2.8, 0.9, 7.8, 0.3, 3.5, 0.1, 6.9, 0.6, 5.2, 0.0, 2.1, 0.7, 8.5, 0.2, 4.1, 0.0, 6.2, 0.8, 5.5, 0.4, 3.0, 1.1, 8.9, 0.3, 3.9, 0.7, 6.0, 1.0, 4.9, 1.5],
    'Is_Delayed': ['No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No']
}

In [ ]:
fleet_data = {
    'Vehicle_ID': [f'VEH_{i}' for i in range(1, 11)],
    'Vehicle_Age_Years': [2, 8, 1, 12, 5, 3, 9, 4, 11, 2],
    'Maintenance_Score': [95, 62, 98, 45, 78, 88, 55, 82, 48, 91],
    'Driver_Experience_Yrs': [8, 3, 12, 2, 6, 9, 4, 7, 1, 10]
}

In [ ]:
weather_data = {
    'Region_ID': [f'REG_{i}' for i in range(1, 6)],
    'Weather_Condition': ['Clear', 'Heavy Rain', 'Fog', 'Clear', 'Storm'],
    'Traffic_Congestion_Index': [2.1, 8.5, 6.2, 3.0, 9.1]
}

In [ ]:
!ls

01_Smart_Employee_Attendance_Prediction
02_Ecommerce_Customer_Churn_Prediction
03_Enterprise_Logistics_Fleet_Delay_Analytics
README.md

In [ ]:
df_shipments = pd.DataFrame(shipments_data)
df_fleet = pd.DataFrame(fleet_data)
df_weather = pd.DataFrame(weather_data)

In [ ]:
with open('03_Enterprise_Logistics_Fleet_Delay_Analytics/data/shipments.csv','w') as file:
  df_shipments.to_csv(file,index=False)

In [ ]:
with open('03_Enterprise_Logistics_Fleet_Delay_Analytics/data/fleet.csv','w') as file:
  df_fleet.to_csv(file,index=False)

In [ ]:
with open('03_Enterprise_Logistics_Fleet_Delay_Analytics/data/weather.csv','w') as file:
  df_weather.to_csv(file,index=False)

In [ ]:
final_df = pd.merge(df_shipments,df_fleet,on='Vehicle_ID')
final_df = pd.merge(final_df,df_weather,on='Region_ID')

In [ ]:
final_df.head()

,Shipment_ID,Vehicle_ID,Region_ID,Distance_KM,Cargo_Weight_Tons,Actual_Delay_Hours,Is_Delayed,Vehicle_Age_Years,Maintenance_Score,Driver_Experience_Yrs,Weather_Condition,Traffic_Congestion_Index
0,SHP_100,VEH_1,REG_1,120,5.2,0.5,No,2,95,8,Clear,2.1
1,SHP_101,VEH_2,REG_2,450,18.0,4.2,Yes,8,62,3,Heavy Rain,8.5
2,SHP_102,VEH_3,REG_3,80,2.1,0.0,No,1,98,12,Fog,6.2
3,SHP_103,VEH_4,REG_4,600,22.5,6.5,Yes,12,45,2,Clear,3.0
4,SHP_104,VEH_5,REG_5,310,12.0,1.2,No,5,78,6,Storm,9.1

In [ ]:
row_count= final_df.shape[0]
col_count = final_df.shape[1]

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Shipment_ID               50 non-null     object
 1   Vehicle_ID                50 non-null     object
 2   Region_ID                 50 non-null     object
 3   Distance_KM               50 non-null     int64
 4   Cargo_Weight_Tons         50 non-null     float64
 5   Actual_Delay_Hours        50 non-null     float64
 6   Is_Delayed                50 non-null     object
 7   Vehicle_Age_Years         50 non-null     int64
 8   Maintenance_Score         50 non-null     int64
 9   Driver_Experience_Yrs     50 non-null     int64
 10  Weather_Condition         50 non-null     object
 11  Traffic_Congestion_Index  50 non-null     float64
dtypes: float64(3), int64(4), object(5)
memory usage: 4.8+ KB

In [ ]:
features = ['Distance_KM','Cargo_Weight_Tons','Actual_Delay_Hours','Vehicle_Age_Years','Maintenance_Score','Driver_Experience_Yrs','Weather_Condition','Traffic_Congestion_Index']
target = ['Is_Delayed']

In [ ]:
tar_imbalance = final_df['Is_Delayed'].value_counts()

In [ ]:
distance_km_mean= final_df.groupby('Is_Delayed')['Distance_KM'].mean()
distance_km_mean

Is_Delayed
No     196.923077
Yes    556.666667
Name: Distance_KM, dtype: float64

In [ ]:
vehicle_main_score = final_df.groupby('Is_Delayed')['Maintenance_Score'].mean()
vehicle_main_score

Is_Delayed
No     77.076923
Yes    71.083333
Name: Maintenance_Score, dtype: float64

In [ ]:
final_df['Prediction'] = np.where((final_df['Distance_KM'] > 400) & (final_df['Maintenance_Score'] < 60) | (final_df['Weather_Condition'].isin(['Storm', 'Heavy Rain'])), 'Yes', 'No')

In [ ]:
total_pred = len(final_df['Prediction'])
correct_pred = (final_df['Prediction'] == final_df['Is_Delayed']).sum()
fn=((final_df['Is_Delayed'] == 'Yes') & (final_df['Prediction'] == 'No')).sum()
fp=((final_df['Is_Delayed'] == 'No') & (final_df['Prediction'] == 'Yes')).sum()
tn=((final_df['Is_Delayed'] == 'No') & (final_df['Prediction'] == 'No')).sum()
tp=((final_df['Is_Delayed'] == 'Yes') & (final_df['Prediction'] == 'Yes')).sum()
rule_accuracy =((tp+tn)/total_pred)*100

In [ ]:
print(f"{'='*10} ENTERPRISE LOGISTICS DELAY ANALYTICS {'='*10}")
print(f"\nIntegrated Dataset Records  : {row_count}")
print(f"Total Combined Features : {col_count}")
print(f"Target Class Distribution  : No = {tar_imbalance.iloc[0]} ({(tar_imbalance.iloc[0]/row_count)*100}%), Yes = {tar_imbalance.iloc[1]} ({(tar_imbalance.iloc[1]/row_count)*100}%)")
print(f"\nGroup Metrics (Delayed vs On-Time):")
print(f"{'-Mean Distance':<25} : Delayed = {distance_km_mean.iloc[0]:.2f} KM | On-Time = {distance_km_mean.iloc[1]:.2f} KM")
print(f"{'-Mean Vehicle Maintenance':<25} : Delayed = {vehicle_main_score.iloc[0]:.2f} Score | On-Time = {vehicle_main_score.iloc[1]:.2f} Score")
print("\nRule Engine Evaluation:")
print(f"{'-Rule Accuracy':<25} : {rule_accuracy:.2f}%")
print(f"{'-False Positives':<25} : {fp}")
print(f"{'-False Negatives':<25} : {fn}")
print("\nConclusion:")
print('''Multi-table integration reveals that severe weather and
low maintenance score interact non-linearly with distance. An ML
algorithm dynamically weights these interactions without hand-coded threshold rules.''')

========== ENTERPRISE LOGISTICS DELAY ANALYTICS ==========

Integrated Dataset Records  : 50
Total Combined Features : 12
Target Class Distribution  : No = 26 (52.0%), Yes = 24 (48.0%)

Group Metrics (Delayed vs On-Time):
-Mean Distance            : Delayed = 196.92 KM | On-Time = 556.67 KM
-Mean Vehicle Maintenance : Delayed = 77.08 Score | On-Time = 71.08 Score

Rule Engine Evaluation:
-Rule Accuracy            : 64.00%
-False Positives          : 10
-False Negatives          : 8

Conclusion:
Multi-table integration reveals that severe weather and
low maintenance score interact non-linearly with distance. An ML
algorithm dynamically weights these interactions without hand-coded threshold rules.