<a href="https://colab.research.google.com/github/shravan1808/ML_SERIES/blob/Main/05_Multi_Class_Patient_Triage_Classification/notebook/Project_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
pat_df=pd.read_csv('patients.csv')

In [3]:
pat_df.head()

  Patient_ID  Heart_Rate_BPM  Systolic_BP  Oxygen_Sat_Pct  Age Triage_Category
0      P_501              72          120              98   35         General
1      P_502             125          165              89   68             ICU
2      P_503              95          138              94   45          Urgent
3      P_504              68          115              99   28         General
4      P_505             140          180              85   75             ICU

In [5]:
pat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Patient_ID       10 non-null     object
 1   Heart_Rate_BPM   10 non-null     int64
 2   Systolic_BP      10 non-null     int64
 3   Oxygen_Sat_Pct   10 non-null     int64
 4   Age              10 non-null     int64
 5   Triage_Category  10 non-null     object
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

In [7]:
df_size = pat_df.shape

In [8]:
pat_df.describe()

       Heart_Rate_BPM  Systolic_BP  Oxygen_Sat_Pct        Age
count       10.000000     10.00000       10.000000  10.000000
mean        95.500000    139.30000       93.600000  48.500000
std         26.850409     23.76295        4.812022  16.015617
min         68.000000    115.00000       85.000000  28.000000
25%         72.750000    120.50000       90.000000  36.250000
50%         90.000000    132.50000       94.500000  47.500000
75%        117.500000    158.25000       97.750000  59.500000
max        140.000000    180.00000       99.000000  75.000000

In [12]:
X = ['Heart_Rate_BPM','Systolic_BP','Oxygen_Sat_Pct','Age']
y = 'Triage_Category'

In [20]:
tar_count = pat_df[y].value_counts()
tar_pct = tar_count/df_size[0]*100

In [48]:
triage_level_mean = pat_df.groupby(y)[X].mean().reset_index()
triage_level_mean

  Triage_Category  Heart_Rate_BPM  Systolic_BP  Oxygen_Sat_Pct        Age
0         General       71.250000   118.750000       98.000000  33.250000
1             ICU      131.666667   171.666667       87.333333  68.333333
2          Urgent       91.666667   134.333333       94.000000  49.000000

In [49]:
print(f"{'='*10} EMERGENCY PATIENT TRIAGE ANALYSIS {'='*10}")
print(f"\n{'Dataset Shape':<27} : {df_size[0]} Rows, {df_size[1]} Columns")
print(f"{'Supervised Paradigm':<27} : Multi Class Classification (Discrete Categorical Target)")
print(f"\n{'Features (X)':<27} : {X[0]},{X[1]},{X[2]},{X[3]}")
print(f"{'Target (y)':<27} : {y}")
print(f"\n{'Class Distribution':<27} :")
for category in ['General', 'Urgent', 'ICU']:
    count = tar_count[category]
    percentage = tar_pct[category]
    print(f"-{category:<26} : {count} ({percentage:.2f}%)")
print(f"\n{'Triage Level Group Averages':<25} :")
print(triage_level_mean.to_string(index= False))
print("\nAlgorithm Guidance: Decision Trees or Multi-Class Logistic Regression are recommended for interpretable clinical rule boundaries.")

========== EMERGENCY PATIENT TRIAGE ANALYSIS ==========

Dataset Shape               : 10 Rows, 6 Columns
Supervised Paradigm         : Multi Class Classification (Discrete Categorical Target)

Features (X)                : Heart_Rate_BPM,Systolic_BP,Oxygen_Sat_Pct,Age
Target (y)                  : Triage_Category

Class Distribution          :
-General                    : 4 (40.00%)
-Urgent                     : 3 (30.00%)
-ICU                        : 3 (30.00%)

Triage Level Group Averages :
Triage_Category  Heart_Rate_BPM  Systolic_BP  Oxygen_Sat_Pct       Age
        General       71.250000   118.750000       98.000000 33.250000
            ICU      131.666667   171.666667       87.333333 68.333333
         Urgent       91.666667   134.333333       94.000000 49.000000

Algorithm Guidance: Decision Trees or Multi-Class Logistic Regression are recommended for interpretable clinical rule boundaries.